include "Common.fbs";
include "Master/Auth.fbs";
include "Master/Heartbeat.fbs";
include "Game/Room.fbs";
include "Game/Movement.fbs";
include "Game/Combat.fbs";
include "Game/Item.fbs";
include "Game/Enemy.fbs";

union PacketType
{
    C_Login,
    S_LoginResult,
    C_Logout,

    C_Heartbeat,
    S_HeartbeatAck,

    C_CreateRoom,
    S_CreateRoom,

    C_JoinRoom,
    S_JoinRoom,

    G_Move,
    H_Move,

    G_Shoot,
    H_Shoot,
    H_ShootRejected,

    H_ItemSpawn,
    H_ItemDespawn,

    G_ItemGain,
    H_ItemGainResult,

    H_ItemBoxUpdate,

    G_ItemExchange,
    H_ItemExchangeResult,

    S_GuestJoined,
    H_GuestJoined,

    G_Equip,
    H_Equip,

    G_ConsumeItem,
    H_ConsumeItemResult,

    G_Durability,
    H_Durability,

    G_GunPartEquip,
    G_GunAmmoSave,
    H_GunState,

    G_StatSync,
    H_StatSync,

    G_Rescue,
    H_Rescue,

    H_EnemySpawn,
    H_EnemyMove,
    H_EnemyHit,
    H_EnemyDie,

    G_Leave,
    H_Leave,

    G_ShelterLevel,
    H_ShelterLevel,

    H_SandbagDestroy,

    H_LoadScene,

    G_SceneReady,

    H_EnemySpeak,

    H_EnemyShoot,

    H_GuestRestore,
}

table FlatPacket
{
    type: PacketType;
}

root_type FlatPacket;
