<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PocoPoachers.Tools.PacketGenerator</RootNamespace>
    <AssemblyName>PocoPoachers.PacketGenerator</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Schemas\**\*.fbs" />
  </ItemGroup>
</Project>
