using System.Diagnostics;
using System.Text;

const string ToolName = "PacketGenerator";

return Run(args);

static int Run(string[] args)
{
    string schemasDir = Path.GetFullPath("Schemas");
    string flatcExe   = Path.GetFullPath("flatc.exe");
    string serverOut  = Path.GetFullPath(Path.Combine("..", "..", "Server", "Server", "Generated", "FlatBuffer"));
    string clientOut  = Path.GetFullPath(Path.Combine("..", "..", "PocoPoachers", "Assets", "01. Scripts", "Generated", "FlatBuffer"));

    for (int i = 0; i < args.Length; i++)
    {
        string a = args[i];
        if      (a == "--schemas") { if (!TryReadValue(args, ref i, out var v)) return 1; schemasDir = v; }
        else if (a == "--server")  { if (!TryReadValue(args, ref i, out var v)) return 1; serverOut  = v; }
        else if (a == "--client")  { if (!TryReadValue(args, ref i, out var v)) return 1; clientOut  = v; }
        else { LogError($"Unknown argument: {a}"); return 1; }
    }

    if (!File.Exists(flatcExe))        { LogError($"flatc.exe not found: {flatcExe}"); return 1; }
    if (!Directory.Exists(schemasDir)) { LogError($"schemas directory not found: {schemasDir}"); return 1; }

    Directory.CreateDirectory(serverOut);
    Directory.CreateDirectory(clientOut);

    var fbsFiles = Directory.GetFiles(schemasDir, "*.fbs");
    if (fbsFiles.Length == 0) { LogError("No .fbs files found."); return 1; }

    LogPath("schemas", schemasDir);
    LogPath("flatc",   flatcExe);
    LogPath("server",  serverOut);
    LogPath("client",  clientOut);
    Console.WriteLine();

    foreach (var fbs in fbsFiles)
    {
        Console.WriteLine($"[{ToolName}] schema: {Path.GetFileName(fbs)}");
        if (RunFlatc(flatcExe, schemasDir, fbs, serverOut) != 0) return 1;
        if (RunFlatc(flatcExe, schemasDir, fbs, clientOut) != 0) return 1;
    }

    if (GeneratePacketManagers(schemasDir, serverOut, clientOut) != 0) return 1;

    Console.WriteLine($"[{ToolName}] Done.");
    return 0;
}

static int GeneratePacketManagers(string schemasDir, string serverOut, string clientOut)
{
    var mainFbs = Path.Combine(schemasDir, "Main.fbs");
    if (!File.Exists(mainFbs)) { LogError($"Main.fbs not found: {mainFbs}"); return 1; }

    var cPackets = new List<string>();
    var sPackets = new List<string>();
    bool inUnion = false;
    foreach (var line in File.ReadAllLines(mainFbs))
    {
        string t = line.Trim();
        if (t.StartsWith("union PacketType")) { inUnion = true; continue; }
        if (!inUnion) continue;
        if (t == "}") break;
        string name = t.TrimEnd(',');
        if      (name.StartsWith("C_")) cPackets.Add(name);
        else if (name.StartsWith("S_")) sPackets.Add(name);
    }

    string serverPacketDir = Path.GetFullPath(Path.Combine(serverOut, "..", "..", "Net", "Packet"));
    string clientPacketDir = Path.GetFullPath(Path.Combine(clientOut, "..", "..", "Network", "Packet"));

    Directory.CreateDirectory(serverPacketDir);
    Directory.CreateDirectory(clientPacketDir);

    File.WriteAllText(
        Path.Combine(serverPacketDir, "PacketManager.Generated.cs"),
        BuildServerPacketManager(cPackets));

    File.WriteAllText(
        Path.Combine(clientPacketDir, "PacketManager.Generated.cs"),
        BuildClientPacketManager(sPackets));

    Console.WriteLine($"[{ToolName}] PacketManager.Generated.cs → server ({cPackets.Count} handlers)");
    Console.WriteLine($"[{ToolName}] PacketManager.Generated.cs → client ({sPackets.Count} handlers)");
    return 0;
}

static string BuildServerPacketManager(List<string> cPackets)
{
    int pad = cPackets.Count > 0 ? cPackets.Max(n => n.Length) : 0;
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated>");
    sb.AppendLine("//  generated by PacketGenerator — do not modify");
    sb.AppendLine("// </auto-generated>");
    sb.AppendLine();
    sb.AppendLine("namespace Server;");
    sb.AppendLine();
    sb.AppendLine("public static partial class PacketManager");
    sb.AppendLine("{");
    sb.AppendLine("    static void Register()");
    sb.AppendLine("    {");
    foreach (var name in cPackets)
        sb.AppendLine($"        _onRecv.Add(PacketType.{name.PadRight(pad)}, _handler.On{name});");
    sb.AppendLine("    }");
    sb.AppendLine("}");
    return sb.ToString();
}

static string BuildClientPacketManager(List<string> sPackets)
{
    int pad = sPackets.Count > 0 ? sPackets.Max(n => n.Length) : 0;
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated>");
    sb.AppendLine("//  generated by PacketGenerator — do not modify");
    sb.AppendLine("// </auto-generated>");
    sb.AppendLine();
    sb.AppendLine("public static partial class PacketManager");
    sb.AppendLine("{");
    sb.AppendLine("    static void Register()");
    sb.AppendLine("    {");
    foreach (var name in sPackets)
        sb.AppendLine($"        _onRecv.Add(PacketType.{name.PadRight(pad)}, PacketHandlers.On{name});");
    sb.AppendLine("    }");
    sb.AppendLine("}");
    return sb.ToString();
}

static bool TryReadValue(string[] args, ref int i, out string value)
{
    value = "";
    if (i + 1 >= args.Length) { LogError($"Missing value for {args[i]}"); return false; }
    value = args[++i];
    return true;
}

static void LogError(string message) =>
    Console.Error.WriteLine($"[Error][{ToolName}] {message}");

static void LogPath(string key, string path) =>
    Console.WriteLine($"[{ToolName}] {key,-18} {path}");

static int RunFlatc(string flatc, string schemasDir, string fbsPath, string outDir)
{
    var psi = new ProcessStartInfo(flatc, $"--csharp --gen-object-api -I \"{schemasDir}\" -o \"{outDir}\" \"{fbsPath}\"")
    {
        UseShellExecute = false,
        RedirectStandardError = true,
    };
    using var p = Process.Start(psi)!;
    string err = p.StandardError.ReadToEnd();
    p.WaitForExit();
    if (p.ExitCode != 0)
    {
        LogError($"flatc failed ({Path.GetFileName(fbsPath)}): exit={p.ExitCode}");
        if (!string.IsNullOrWhiteSpace(err))
            Console.Error.WriteLine(err);
    }
    return p.ExitCode;
}
