using System.Diagnostics;
using System.Text;

const string ToolName = "PacketGenerator";

return Run(args);

static int Run(string[] args)
{
    string schemasDir = Path.GetFullPath("Schemas");
    string flatcExe = Path.GetFullPath("flatc.exe");
    string serverOut = Path.GetFullPath(Path.Combine("..", "..", "Server", "Server", "Generated", "FlatBuffer"));
    string clientOut = Path.GetFullPath(Path.Combine("..", "..", "PocoPoachers", "Assets", "01. Scripts", "Generated", "FlatBuffer"));

    for (int i = 0; i < args.Length; i++)
    {
        string a = args[i];
        if (a == "--schemas") { if (!TryReadValue(args, ref i, out var v)) return 1; schemasDir = v; }
        else if (a == "--server") { if (!TryReadValue(args, ref i, out var v)) return 1; serverOut = v; }
        else if (a == "--client") { if (!TryReadValue(args, ref i, out var v)) return 1; clientOut = v; }
        else { LogError($"Unknown argument: {a}"); return 1; }
    }

    if (!File.Exists(flatcExe)) { LogError($"flatc.exe not found: {flatcExe}"); return 1; }
    if (!Directory.Exists(schemasDir)) { LogError($"schemas directory not found: {schemasDir}"); return 1; }

    Directory.CreateDirectory(serverOut);
    Directory.CreateDirectory(clientOut);

    var fbsFiles = Directory.GetFiles(schemasDir, "*.fbs", SearchOption.AllDirectories);
    if (fbsFiles.Length == 0) { LogError("No .fbs files found."); return 1; }

    LogPath("schemas", schemasDir);
    LogPath("flatc", flatcExe);
    LogPath("server", serverOut);
    LogPath("client", clientOut);
    Console.WriteLine();

    foreach (var fbs in fbsFiles)
    {
        Console.WriteLine($"[{ToolName}] schema: {Path.GetFileName(fbs)}");
        if (RunFlatc(flatcExe, schemasDir, fbs, serverOut) != 0) return 1;
        if (RunFlatc(flatcExe, schemasDir, fbs, clientOut) != 0) return 1;
    }

    if (!ParseMainFbs(schemasDir, out var cPackets, out var sPackets)) return 1;
    if (GeneratePacketManagers(serverOut, clientOut, cPackets, sPackets) != 0) return 1;
    if (GenerateHandlerStubs(schemasDir, serverOut, clientOut) != 0) return 1;

    Console.WriteLine($"[{ToolName}] Done.");
    return 0;
}

// C_ → 서버 등록, S_/G_/H_ → 클라이언트 등록
static bool ParseMainFbs(string schemasDir, out List<string> cPackets, out List<string> sPackets)
{
    cPackets = new List<string>();
    sPackets = new List<string>();
    var mainFbs = Path.Combine(schemasDir, "Main.fbs");
    if (!File.Exists(mainFbs)) { LogError($"Main.fbs not found: {mainFbs}"); return false; }

    bool inUnion = false;
    foreach (var line in File.ReadAllLines(mainFbs))
    {
        string t = line.Trim();
        if (t.StartsWith("union PacketType")) { inUnion = true; continue; }
        if (!inUnion) continue;
        if (t == "}") break;
        string name = t.Split("//")[0].Trim().TrimEnd(',');
        if (name.StartsWith("C_")) cPackets.Add(name);
        else if (name.StartsWith("S_") || name.StartsWith("G_") || name.StartsWith("H_")) sPackets.Add(name);
    }
    return true;
}

static int GeneratePacketManagers(string serverOut, string clientOut,
    List<string> cPackets, List<string> sPackets)
{
    string serverPacketDir = Path.GetFullPath(Path.Combine(serverOut, "..", "..", "Net", "Packet"));
    string clientPacketDir = Path.GetFullPath(Path.Combine(clientOut, "..", "..", "Network", "Packet"));

    Directory.CreateDirectory(serverPacketDir);
    Directory.CreateDirectory(clientPacketDir);

    File.WriteAllText(
        Path.Combine(serverPacketDir, "PacketManager.Generated.cs"),
        BuildServerPacketManager(cPackets));

    File.WriteAllText(
        Path.Combine(clientPacketDir, "PacketManager.Generated.cs"),
        BuildClientPacketManager(sPackets));

    Console.WriteLine($"[{ToolName}] PacketManager.Generated.cs -> server ({cPackets.Count} handlers)");
    Console.WriteLine($"[{ToolName}] PacketManager.Generated.cs -> client ({sPackets.Count} handlers)");
    return 0;
}

static string BuildServerPacketManager(List<string> cPackets)
{
    int pad = cPackets.Count > 0 ? cPackets.Max(n => n.Length) : 0;
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated>");
    sb.AppendLine("//  generated by PacketGenerator — do not modify");
    sb.AppendLine("// </auto-generated>");
    sb.AppendLine();
    sb.AppendLine("namespace Server;");
    sb.AppendLine();
    sb.AppendLine("public static partial class PacketManager");
    sb.AppendLine("{");
    sb.AppendLine("    static void Register()");
    sb.AppendLine("    {");
    foreach (var name in cPackets)
        sb.AppendLine($"        _onRecv.Add(PacketType.{name.PadRight(pad)}, _handler.On{name});");
    sb.AppendLine("    }");
    sb.AppendLine("}");
    return sb.ToString();
}

static string BuildClientPacketManager(List<string> sPackets)
{
    int pad = sPackets.Count > 0 ? sPackets.Max(n => n.Length) : 0;
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated>");
    sb.AppendLine("//  generated by PacketGenerator — do not modify");
    sb.AppendLine("// </auto-generated>");
    sb.AppendLine();
    sb.AppendLine("public static partial class PacketManager");
    sb.AppendLine("{");
    sb.AppendLine("    static void Register()");
    sb.AppendLine("    {");
    foreach (var name in sPackets)
        sb.AppendLine($"        _onRecv.Add(PacketType.{name.PadRight(pad)}, PacketHandlers.On{name});");
    sb.AppendLine("    }");
    sb.AppendLine("}");
    return sb.ToString();
}

static int GenerateHandlerStubs(string schemasDir, string serverOut, string clientOut)
{
    // 1. 디렉터리 경로 설정
    string serverHandlerDir = Path.GetFullPath(Path.Combine(serverOut, "..", "..", "Net", "Packet", "PacketHandler"));

    // 클라이언트용 세분화된 경로
    string clientHandlerSDir = Path.GetFullPath(Path.Combine(clientOut, "..", "..", "Network", "Packet", "SPacketHandlers"));
    string clientHandlerGDir = Path.GetFullPath(Path.Combine(clientOut, "..", "..", "Network", "Packet", "GPacketHandlers"));
    string clientHandlerHDir = Path.GetFullPath(Path.Combine(clientOut, "..", "..", "Network", "Packet", "HPacketHandlers"));

    // 2. 디렉터리 생성
    Directory.CreateDirectory(serverHandlerDir);
    Directory.CreateDirectory(clientHandlerSDir);
    Directory.CreateDirectory(clientHandlerGDir);
    Directory.CreateDirectory(clientHandlerHDir);

    // 3. 기존 구현된 메서드 수집
    var existingServer = CollectImplementedMethods(serverHandlerDir, "OnC_");

    // 클라이언트는 S/G/H 디렉터리 모두에서 수집
    var existingClient = new HashSet<string>();
    existingClient.UnionWith(CollectImplementedMethods(clientHandlerSDir, "OnS_"));
    existingClient.UnionWith(CollectImplementedMethods(clientHandlerGDir, "OnG_"));
    existingClient.UnionWith(CollectImplementedMethods(clientHandlerHDir, "OnH_"));

    var skip = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "Main.fbs", "Common.fbs" };

    foreach (var fbsPath in Directory.GetFiles(schemasDir, "*.fbs", SearchOption.AllDirectories))
    {
        if (skip.Contains(Path.GetFileName(fbsPath))) continue;

        string schema = Path.GetFileNameWithoutExtension(fbsPath);
        var cPackets = new List<string>();
        var sPackets = new List<string>();
        var gPackets = new List<string>();
        var hPackets = new List<string>();

        // FBS 파일 파싱
        foreach (var line in File.ReadAllLines(fbsPath))
        {
            string t = line.Trim();
            if (!t.StartsWith("table ")) continue;
            string name = t["table ".Length..].TrimEnd('{').Trim();

            if (name.StartsWith("C_")) cPackets.Add(name);
            else if (name.StartsWith("S_")) sPackets.Add(name);
            else if (name.StartsWith("G_")) gPackets.Add(name);
            else if (name.StartsWith("H_")) hPackets.Add(name);
        }

        // --- 파일 쓰기 (미구현 패킷이 있을 때만 생성) ---

        // 서버 (C_)
        var cPkt = cPackets.Where(n => !existingServer.Contains($"On{n}")).ToList();
        if (cPkt.Count > 0)
            WriteHandlerFile(serverHandlerDir, $"PacketHandler.{schema}", BuildServerHandlerStubs(schema, cPkt));

        // 클라 (S_) -> SPacketHandlers 폴더로
        var sPkt = sPackets.Where(n => !existingClient.Contains($"On{n}")).ToList();
        if (sPkt.Count > 0)
            WriteHandlerFile(clientHandlerSDir, $"PacketHandler.{schema}", BuildClientHandlerStubs(schema, sPkt));

        // 클라 (G_) -> GPacketHandlers 폴더로
        var gPkt = gPackets.Where(n => !existingClient.Contains($"On{n}")).ToList();
        if (gPkt.Count > 0)
            WriteHandlerFile(clientHandlerGDir, $"PacketHandler.{schema}", BuildClientHandlerStubs(schema, gPkt));

        // 클라 (H_) -> HPacketHandlers 폴더로
        var hPkt = hPackets.Where(n => !existingClient.Contains($"On{n}")).ToList();
        if (hPkt.Count > 0)
            WriteHandlerFile(clientHandlerHDir, $"PacketHandler.{schema}", BuildClientHandlerStubs(schema, hPkt));
    }

    return 0;
}

// 파일이 이미 있으면 .temp.cs, 없으면 .cs로 저장
static void WriteHandlerFile(string dir, string baseName, string content)
{
    string normal = Path.Combine(dir, $"{baseName}.cs");
    string temp = Path.Combine(dir, $"{baseName}.temp.cs");

    if (File.Exists(normal))
    {
        // 내용이 빈 스텁 클래스뿐이면 temp 불필요
        if (string.IsNullOrWhiteSpace(content) || IsEmptyClass(content))
        {
            if (File.Exists(temp)) File.Delete(temp);
            return;
        }
        File.WriteAllText(temp, content);
        Console.WriteLine($"[{ToolName}]   {Path.GetFileName(temp)} (temp — merge manually)");
    }
    else
    {
        File.WriteAllText(normal, content);
        Console.WriteLine($"[{ToolName}]   {Path.GetFileName(normal)}");
    }
}

// 스텁 메서드가 하나도 없는 빈 클래스인지 확인
static bool IsEmptyClass(string content)
    => !content.Contains("// TODO");

static HashSet<string> CollectImplementedMethods(string dir, string prefix)
{
    var result = new HashSet<string>();
    if (!Directory.Exists(dir)) return result;
    foreach (var file in Directory.GetFiles(dir, "*.cs"))
    {
        if (file.EndsWith(".temp.cs", StringComparison.OrdinalIgnoreCase)) continue;
        foreach (var line in File.ReadAllLines(file))
        {
            int idx = line.IndexOf(prefix, StringComparison.Ordinal);
            if (idx < 0 || !line.Contains('(')) continue;
            int end = line.IndexOf('(', idx);
            string method = line[idx..end].Trim();
            if (method.Length > prefix.Length) result.Add(method);
        }
    }
    return result;
}

static string BuildServerHandlerStubs(string schema, List<string> packets)
{
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated>");
    sb.AppendLine($"//  generated by PacketGenerator ({schema}.fbs)");
    sb.AppendLine("// </auto-generated>");
    sb.AppendLine();
    sb.AppendLine("namespace Server;");
    sb.AppendLine();
    sb.AppendLine("public partial class PacketHandler");
    sb.AppendLine("{");
    for (int i = 0; i < packets.Count; i++)
    {
        if (i > 0) sb.AppendLine();
        sb.AppendLine($"    public void On{packets[i]}(ClientSession session, FlatPacket root)");
        sb.AppendLine("    {");
        sb.AppendLine("        // TODO");
        sb.AppendLine("    }");
    }
    sb.AppendLine("}");
    return sb.ToString();
}

static string BuildClientHandlerStubs(string schema, List<string> packets)
{
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated>");
    sb.AppendLine($"//  generated by PacketGenerator ({schema}.fbs)");
    sb.AppendLine("// </auto-generated>");
    sb.AppendLine();
    sb.AppendLine("public static partial class PacketHandlers");
    sb.AppendLine("{");
    for (int i = 0; i < packets.Count; i++)
    {
        if (i > 0) sb.AppendLine();
        sb.AppendLine($"    public static void On{packets[i]}(FlatPacket root)");
        sb.AppendLine("    {");
        sb.AppendLine("        // TODO");
        sb.AppendLine("    }");
    }
    sb.AppendLine("}");
    return sb.ToString();
}

static bool TryReadValue(string[] args, ref int i, out string value)
{
    value = "";
    if (i + 1 >= args.Length) { LogError($"Missing value for {args[i]}"); return false; }
    value = args[++i];
    return true;
}

static void LogError(string message) =>
    Console.Error.WriteLine($"[Error][{ToolName}] {message}");

static void LogPath(string key, string path) =>
    Console.WriteLine($"[{ToolName}] {key,-18} {path}");

static int RunFlatc(string flatc, string schemasDir, string fbsPath, string outDir)
{
    var psi = new ProcessStartInfo(flatc, $"--csharp --gen-object-api -I \"{schemasDir}\" -o \"{outDir}\" \"{fbsPath}\"")
    {
        UseShellExecute = false,
        RedirectStandardError = true,
    };
    using var p = Process.Start(psi)!;
    string err = p.StandardError.ReadToEnd();
    p.WaitForExit();
    if (p.ExitCode != 0)
    {
        LogError($"flatc failed ({Path.GetFileName(fbsPath)}): exit={p.ExitCode}");
        if (!string.IsNullOrWhiteSpace(err))
            Console.Error.WriteLine(err);
    }
    return p.ExitCode;
}
