// <auto-generated>
//  generated by PacketGenerator (Item.fbs)
// </auto-generated>

public static partial class PacketHandlers
{
    public static void OnG_ItemGain(FlatPacket root)
    {
        // TODO
    }

    public static void OnG_ItemExchange(FlatPacket root)
    {
        // TODO
    }
}
