// <auto-generated>
//  generated by PacketGenerator (Ping.fbs)
// </auto-generated>

using System;

public static partial class PacketHandlers
{
    public static void OnS_PongRes(FlatPacket root)
    {
        var pkt = root.TypeAsS_PongRes();
        long rtt = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds() - pkt.SendTime;
        MainThreadDispatcher.Enqueue(() => NetworkManager.Instance?.OnPongRes(rtt));
    }
}
