// <auto-generated>
//  generated by PacketGenerator (Room.fbs)
// </auto-generated>

public static partial class PacketHandlers
{
    public static void OnS_CreateRoom(FlatPacket root)
    {
        // TODO
    }

    public static void OnS_JoinRoom(FlatPacket root)
    {
        // TODO
    }
}
