include "Common.fbs";

table H_EnemySpawn
{
    enemy_type_id: int;
    enemy_id: int;
    pos:      Vec3;
    rotation: float;
    hp:       float;
    max_hp:   float;
    weapon_id: int;
    helmet_id: int;
}

table H_EnemyMove
{
    enemy_id:   int;
    pos:        Vec3;
    rotation:   float;
    anim_state: int;
}

table H_EnemyHit
{
    enemy_id: int;
    hp:       float;
    max_hp:   float;
    damage:   float;
}

table H_EnemyDie
{
    enemy_id: int;
}

table H_EnemySpeak
{
    enemy_id: int;
    message:  string;
    duration: float;
}

table H_EnemyShoot
{
    enemy_id:     int;
    origin:       Vec3;
    direction:    Vec3;
    bullet_speed: float;
    damage:       float;
    max_range:    float;
    directions:   [Vec3]; // 샷건 등 다발 발사의 펠릿별 방향. 비어 있으면 direction 단발
}
