include "Common.fbs";

table InventoryItem
{
    item_id: int;
    amount:  int;
}

table H_ItemSpawn
{
    uid:      int;
    type_id:  int;
    pos:      Vec3;
    rotation: float;
    item_ids: [int];
}

table H_ItemDespawn
{
    uid: int;
}

table G_ItemGain
{
    is_player_gained: bool;
    box_uid:      int;
    item_type_id: int;
    amount:       int;
    added_slot_index: int;
    removed_slot_index:   int;
}

table H_ItemGainResult
{
    success:            bool;
    box_uid:            int;
    item_type_id:       int;
    amount:             int;
    player_slot_index:  int = -1;
}

table H_ItemBoxUpdate
{
    box_uid: int;
    item_type_id: int;
    amount: int;
    slot_index: int;
}

table H_InventoryUpdate
{
    player_id: int;
    items:     [InventoryItem];
}

table G_ItemExchange
{
    box_uid:            int;
    player_item_id:     int;
    player_item_amount: int;
    player_slot_index:  int;
    box_item_id:        int;
    box_item_amount:    int;
    box_slot_index:     int;
}

table H_ItemExchangeResult
{
    success:            bool;
    box_uid:            int;
    player_item_id:     int;
    player_item_amount: int;
    player_slot_index:  int;
    box_item_id:        int;
    box_item_amount:    int;
    box_slot_index:     int;
}

table G_ConsumeItem
{
    item_id: int;
    amount: int;
    inventory_index: int;
}

table H_ConsumeItemResult
{
    is_success: bool;
    item_id: int;
    amount: int;
    inventory_index: int;
}

// item_id = 0 이면 해제
table G_Equip
{
    player_id:  int;
    item_id:    int;
    slot_index: int;
}

table H_Equip
{
    player_id:  int;
    item_id:    int;
    slot_index: int;
}