include "Common.fbs";

table NetInfo
{
    player_id: int;
    public_ip: string;
    public_port: ushort;
    private_ip: string;
    private_port: ushort;
}

table C_CreateRoom
{
    my_info: NetInfo;
}

table S_CreateRoom
{
    session_code: string;
    success: bool;
}

table C_JoinRoom
{
    session_code: string;
    my_info: NetInfo;
}

table S_JoinRoom
{
    success: bool;
    host_info: NetInfo;
}

table S_GuestJoined
{
    info: NetInfo;
}

table H_GuestJoined
{
    info: [PlayerInfo];
}

table G_Leave
{
    player_id: int;
}

table H_Leave
{
    player_id: int;
    is_host:   bool;
}

table G_ShelterLevel
{
    level: int;
}

table H_ShelterLevel
{
    level: int;
}