include "Common.fbs";
include "Auth.fbs";
include "Movement.fbs";
include "Inventory.fbs";
include "WorldItem.fbs";
include "Combat.fbs";
include "Ping.fbs";
include "P2PConnect.fbs";

union PacketType
{
    C_LoginReq,
    S_LoginRes,

    C_MoveReq,
    S_MoveNtf,

    S_InventoryNtf,

    S_WorldItemDespawnNtf,

    C_ShootReq,
    S_ShootNtf,

    S_SpawnItemBoxNtf,
    C_GainItemReq,
    S_ChangeItemBox,
    S_SuccessGainItemNtf,
    C_ExchangeItemReq,
    S_ExchangeItemResultNtf,

    C_PingReq,
    S_PongRes,

    C_RegisterP2PSession,
    S_RegisterP2PSessionRes,
    C_JoinP2PSession,
    S_P2PSessionInfo,
    S_PeerJoined,
}

table FlatPacket
{
    type: PacketType;
}

root_type FlatPacket;
