include "Common.fbs";
include "Auth.fbs";
include "Movement.fbs";
include "Inventory.fbs";
include "WorldItem.fbs";
include "Combat.fbs";

union PacketType
{
    C_LoginReq,
    S_LoginRes,

    C_MoveReq,
    S_MoveNtf,

    S_InventoryNtf,

    S_WorldItemDespawnNtf,

    C_ShootReq,
    S_ShootNtf,
    
    S_SpawnItemBoxNtf,
    C_GainItemReq,
    S_ChangeItemBox,
    S_SuccessGainItemNtf,
    C_ExchangeItemReq,
    S_ExchangeItemResultNtf,
}

table FlatPacket
{
    type: PacketType;
}

root_type FlatPacket;
