include "Common.fbs";

table C_RegisterP2PSession
{
    session_code  : string;
    public_ip     : string;
    public_port   : ushort;
    private_ip    : string;
    private_port  : ushort;
}

table S_RegisterP2PSessionRes
{
    success : bool;
}

table C_JoinP2PSession
{
    session_code : string;
}

table S_P2PSessionInfo
{
    host_public_ip    : string;
    host_public_port  : ushort;
    host_private_ip   : string;
    host_private_port : ushort;
}

table S_PeerJoined
{
    peer_public_ip   : string;
    peer_public_port : ushort;
}
