include "Common.fbs";


table S_WorldItemDespawnNtf
{
    uid: int;
}

table S_SpawnItemBoxNtf
{
    uid: int;
    type_id: int;
    pos: Vec3;
    rotation: float;
    item_ids: [int];
}

table C_GainItemReq
{
    is_player: bool;
    box_uid: int;
    item_uid: int;
    amount: int;
    slot_index: int;
    removed_slot_index: int;
}

table S_ChangeItemBox
{
    is_gain: bool;
    box_uid: int;
    type_id: int;
    amount: int;
    slot_index: int;
}

table S_SuccessGainItemNtf
{
    uid: int;
    type_id: int;
    amount: int;
    slot_index: int;
    removed_slot_index: int;
}

table C_ExchangeItemReq
{
    box_uid: int;
    player_item_id: int;
    player_item_amount: int;
    player_slot_index: int;
    box_item_id: int;
    box_item_amount: int;
    box_slot_index: int;
}

table S_ExchangeItemResultNtf
{
    is_success: bool;
    box_uid: int;
    player_gain_item_id: int;
    player_gain_item_amount: int;
    player_slot_index: int;
    box_gain_item_id: int;
    box_gain_item_amount: int;
    box_slot_index: int;
}