// <auto-generated>
//  generated by PacketGenerator (Movement.fbs)
// </auto-generated>

public static partial class PacketHandlers
{
    public static void OnH_Move(FlatPacket root)
    {
        // TODO
    }
}
