// <auto-generated>
//  generated by PacketGenerator (Combat.fbs)
// </auto-generated>

public static partial class PacketHandlers
{
    public static void OnH_Shoot(FlatPacket root)
    {
        // TODO
    }
}
