// <auto-generated>
//  generated by PacketGenerator (Room.fbs)
// </auto-generated>

namespace Server;

public partial class PacketHandler
{
    public void OnC_CreateRoom(ClientSession session, FlatPacket root)
    {
        // TODO
    }

    public void OnC_JoinRoom(ClientSession session, FlatPacket root)
    {
        // TODO
    }
}
