// <auto-generated>
//  generated by PacketGenerator (Inventory.fbs)
// </auto-generated>

namespace Server;

public partial class PacketHandler
{
    public void OnC_ConsumeItem(ClientSession session, FlatPacket root)
    {
        var pkt = root.TypeAsC_ConsumeItem();
        if (session.Player is not { } player)
            return;

        int itemTypeId = pkt.ItemId;
        int amount = pkt.Amount;
        int slotIndex = pkt.InventoryIndex;

        if (!session.Player.Inventory.RemoveItem(itemTypeId, amount))
        {
            LOG_W($"아이템 사용 실패(ID : {itemTypeId}, 수량 : {amount}");
            return;
        }
        else
            LOG("아이템 사용");
    }
}
