using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Nodes;

// ── 기본 경로 (bat에서 실행 시 TableGenerator 폴더가 작업 디렉터리)
string dataDir       = "Data";
string serverCsOut   = Path.Combine("..", "..", "Server", "Generated", "Table");
string clientCsOut   = Path.Combine("..", "..", "..", "PocoPoachers", "Assets", "01. Scripts", "Generated", "Table");
string jsonOut       = Path.Combine("..", "..", "Server", "Data", "Table");

for (int i = 0; i < args.Length; i++)
{
    if (args[i] == "--data"       && i + 1 < args.Length) dataDir     = args[++i];
    if (args[i] == "--cs-server"  && i + 1 < args.Length) serverCsOut = args[++i];
    if (args[i] == "--cs-client"  && i + 1 < args.Length) clientCsOut = args[++i];
    if (args[i] == "--json"       && i + 1 < args.Length) jsonOut     = args[++i];
}

serverCsOut = Path.GetFullPath(serverCsOut);
clientCsOut = Path.GetFullPath(clientCsOut);
jsonOut     = Path.GetFullPath(jsonOut);

Directory.CreateDirectory(serverCsOut);
Directory.CreateDirectory(clientCsOut);
Directory.CreateDirectory(jsonOut);

Console.WriteLine($"Server CS output : {serverCsOut}");
Console.WriteLine($"Client CS output : {clientCsOut}");
Console.WriteLine($"JSON output      : {jsonOut}");
Console.WriteLine();

foreach (var csvPath in Directory.GetFiles(dataDir, "*.csv"))
    ProcessCsv(csvPath);

Console.WriteLine("Done.");
return;

// ────────────────────────────────────────────────
void ProcessCsv(string csvPath)
{
    string fileName  = Path.GetFileNameWithoutExtension(csvPath);
    string className = ToPascalCase(fileName); // items → Items

    var (headers, rows) = ReadCsv(csvPath);
    if (headers.Length == 0 || rows.Count == 0) return;

    var types = InferTypes(headers, rows);

    WriteServerCs(serverCsOut, className, headers, types);
    WriteClientCs(clientCsOut, className, headers, types);
    WriteJson(jsonOut, fileName, headers, types, rows);

    Console.WriteLine($"{fileName}.csv");
}

// ── CSV 파싱 ─────────────────────────────────────
(string[] headers, List<string[]> rows) ReadCsv(string path)
{
    var lines = File.ReadAllLines(path, Encoding.UTF8);
    if (lines.Length < 2) return ([], []);

    var headers = SplitCsvLine(lines[0]);
    var rows    = new List<string[]>();
    for (int i = 1; i < lines.Length; i++)
    {
        var cols = SplitCsvLine(lines[i]);
        if (cols.Length > 0) rows.Add(cols);
    }
    return (headers, rows);
}

string[] SplitCsvLine(string line)
{
    // 따옴표 미지원 단순 분할 (기본 케이스)
    var parts = line.Split(',');
    for (int i = 0; i < parts.Length; i++) parts[i] = parts[i].Trim();
    return parts;
}

// ── 타입 추론 ─────────────────────────────────────
string[] InferTypes(string[] headers, List<string[]> rows)
{
    var types = new string[headers.Length];
    for (int col = 0; col < headers.Length; col++)
    {
        bool allInt   = true;
        bool allFloat = true;
        foreach (var row in rows)
        {
            string val = col < row.Length ? row[col] : "";
            if (!int.TryParse(val, out _))   allInt   = false;
            if (!float.TryParse(val, System.Globalization.NumberStyles.Float,
                                System.Globalization.CultureInfo.InvariantCulture, out _))
                allFloat = false;
        }
        types[col] = allInt ? "int" : allFloat ? "float" : "string";
    }
    return types;
}

// ── 서버용 C# 코드 생성 (record + System.Text.Json) ──
void WriteServerCs(string outDir, string className, string[] headers, string[] types)
{
    int keyIdx     = Array.FindIndex(types, t => t == "int");
    string keyType = keyIdx >= 0 ? "int" : "string";
    string keyProp = keyIdx >= 0 ? ToPascalCase(headers[keyIdx]) : ToPascalCase(headers[0]);

    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated>");
    sb.AppendLine("using System.Text.Json.Serialization;");
    sb.AppendLine();
    sb.AppendLine($"public record {className}Data");
    sb.AppendLine("{");
    for (int i = 0; i < headers.Length; i++)
    {
        string prop   = ToPascalCase(headers[i]);
        string type   = types[i];
        string defVal = type == "string" ? " = \"\";" : "";
        sb.AppendLine($"    [JsonPropertyName(\"{headers[i]}\")] public {type} {prop} {{ get; init; }}{defVal}");
    }
    sb.AppendLine("}");
    File.WriteAllText(Path.Combine(outDir, $"{className}Data.cs"), sb.ToString(), Encoding.UTF8);

    sb.Clear();
    sb.AppendLine("// <auto-generated>");
    sb.AppendLine("#nullable enable");
    sb.AppendLine("using System.Text.Json;");
    sb.AppendLine();
    sb.AppendLine($"public static class {className}Table");
    sb.AppendLine("{");
    sb.AppendLine($"    static readonly Dictionary<{keyType}, {className}Data> _map = new();");
    sb.AppendLine();
    sb.AppendLine($"    public static void Load(string json)");
    sb.AppendLine("    {");
    sb.AppendLine($"        var list = JsonSerializer.Deserialize<List<{className}Data>>(json)!;");
    sb.AppendLine("        _map.Clear();");
    sb.AppendLine($"        foreach (var d in list) _map[d.{keyProp}] = d;");
    sb.AppendLine("    }");
    sb.AppendLine();
    sb.AppendLine($"    public static {className}Data? Get({keyType} key) => _map.GetValueOrDefault(key);");
    sb.AppendLine($"    public static IReadOnlyCollection<{className}Data> All => _map.Values;");
    sb.AppendLine("}");
    File.WriteAllText(Path.Combine(outDir, $"{className}Table.cs"), sb.ToString(), Encoding.UTF8);
}

// ── Unity 클라이언트용 C# 코드 생성 ([Serializable] + JsonUtility) ──
void WriteClientCs(string outDir, string className, string[] headers, string[] types)
{
    int keyIdx      = Array.FindIndex(types, t => t == "int");
    string keyType  = keyIdx >= 0 ? "int" : "string";
    string keyField = keyIdx >= 0 ? headers[keyIdx] : headers[0];

    // *Data.cs — public 필드, JsonUtility가 필드명으로 매핑
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated>");
    sb.AppendLine("using System;");
    sb.AppendLine();
    sb.AppendLine("[Serializable]");
    sb.AppendLine($"public class {className}Data");
    sb.AppendLine("{");
    for (int i = 0; i < headers.Length; i++)
    {
        string type   = types[i];
        string defVal = type == "string" ? " = \"\"" : "";
        sb.AppendLine($"    public {type} {headers[i]}{defVal};");
    }
    sb.AppendLine("}");
    File.WriteAllText(Path.Combine(outDir, $"{className}Data.cs"), sb.ToString(), Encoding.UTF8);

    // *Table.cs — JsonUtility로 로드
    sb.Clear();
    sb.AppendLine("// <auto-generated>");
    sb.AppendLine("#nullable enable");
    sb.AppendLine("using System;");
    sb.AppendLine("using System.Collections.Generic;");
    sb.AppendLine("using UnityEngine;");
    sb.AppendLine();
    sb.AppendLine($"public static class {className}Table");
    sb.AppendLine("{");
    sb.AppendLine($"    [Serializable] class DataArray {{ public {className}Data[] items = Array.Empty<{className}Data>(); }}");
    sb.AppendLine($"    static readonly Dictionary<{keyType}, {className}Data> _map = new Dictionary<{keyType}, {className}Data>();");
    sb.AppendLine();
    sb.AppendLine($"    public static void Load(string json)");
    sb.AppendLine("    {");
    sb.AppendLine($"        var arr = JsonUtility.FromJson<DataArray>(\"{{\\\"items\\\":\" + json + \"}}\");");
    sb.AppendLine("        _map.Clear();");
    sb.AppendLine($"        foreach (var d in arr.items) _map[d.{keyField}] = d;");
    sb.AppendLine("    }");
    sb.AppendLine();
    sb.AppendLine($"    public static {className}Data? Get({keyType} key) => _map.TryGetValue(key, out var v) ? v : null;");
    sb.AppendLine($"    public static IEnumerable<{className}Data> All => _map.Values;");
    sb.AppendLine("}");
    File.WriteAllText(Path.Combine(outDir, $"{className}Table.cs"), sb.ToString(), Encoding.UTF8);
}

// ── JSON 생성 ─────────────────────────────────────
void WriteJson(string outDir, string fileName, string[] headers, string[] types, List<string[]> rows)
{
    var array = new JsonArray();
    foreach (var row in rows)
    {
        var obj = new JsonObject();
        for (int i = 0; i < headers.Length; i++)
        {
            string raw = i < row.Length ? row[i] : "";
            if (types[i] == "int" && int.TryParse(raw, out int iv))
                obj[headers[i]] = iv;
            else if (types[i] == "float" && float.TryParse(raw,
                     System.Globalization.NumberStyles.Float,
                     System.Globalization.CultureInfo.InvariantCulture, out float fv))
                obj[headers[i]] = fv;
            else
                obj[headers[i]] = raw;
        }
        array.Add(obj);
    }

    var opts = new JsonSerializerOptions { WriteIndented = true, Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping };
    string json = array.ToJsonString(opts);
    File.WriteAllText(Path.Combine(outDir, $"{fileName}.json"), json, Encoding.UTF8);
}

// ── snake_case → PascalCase ──────────────────────
string ToPascalCase(string s)
{
    var sb = new StringBuilder();
    bool upper = true;
    foreach (char c in s)
    {
        if (c == '_') { upper = true; continue; }
        sb.Append(upper ? char.ToUpper(c) : c);
        upper = false;
    }
    return sb.ToString();
}
