// <auto-generated>
//  generated by PacketGenerator — do not modify
// </auto-generated>

public static partial class PacketManager
{
    static void Register()
    {
        _onRecv.Add(PacketType.S_LoginRes             , PacketHandlers.OnS_LoginRes);
        _onRecv.Add(PacketType.S_MoveNtf              , PacketHandlers.OnS_MoveNtf);
        _onRecv.Add(PacketType.S_InventoryNtf         , PacketHandlers.OnS_InventoryNtf);
        _onRecv.Add(PacketType.S_WorldItemDespawnNtf  , PacketHandlers.OnS_WorldItemDespawnNtf);
        _onRecv.Add(PacketType.S_ShootNtf             , PacketHandlers.OnS_ShootNtf);
        _onRecv.Add(PacketType.S_SpawnItemBoxNtf      , PacketHandlers.OnS_SpawnItemBoxNtf);
        _onRecv.Add(PacketType.S_ChangeItemBox        , PacketHandlers.OnS_ChangeItemBox);
        _onRecv.Add(PacketType.S_SuccessGainItemNtf   , PacketHandlers.OnS_SuccessGainItemNtf);
        _onRecv.Add(PacketType.S_ExchangeItemResultNtf, PacketHandlers.OnS_ExchangeItemResultNtf);
    }
}
